# Any time Docker is used 'sudo' is required
sudo: required

# Install copy of docker in running container
services:
  - docker

# Build docker image before test are run
before_install:
  - docker build -t dvsdockermtl/docker-react -f Dockerfile.dev .

# Commands to run test suite
# -- --watchAll=false to exit test so it is not hanging
script:
  - docker run -e CI=true dvsdockermtl/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-705957825205"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"